require("nvim-treesitter.configs").setup({
	ensure_installed = {
		"lua",
		"vim",
		"vimdoc",
		"javascript",
		"typescript",
		"tsx",
		"json",
		"rust",
		"bash",
		"regex",
		"markdown",
		"markdown_inline",
		"yaml",
		"ruby",
	},
	highlight = { enable = true },
	indent = { enable = true },
})
